// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations and introspection must use Neon's *direct* (unpooled)
    // endpoint — the pooled endpoint runs PgBouncer in transaction mode,
    // which breaks DDL. Falls back to DATABASE_URL for single-URL setups.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
